In [22]:
zoo.groupby('animal')['water_need'].sum()

animal
elephant    1650
tiger       1550
zebra        200
Name: water_need, dtype: int64

In [23]:
result_Group = df.groupby('Category')[['Value', 'Fee', 'Discount']].aggregate('sum')

print(result_Group)

          Value     Fee  Discount
Category
A            95  109000      5800
B           130  139000      6300

In [24]:
result_group = df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

result_group

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [25]:
df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [26]:
zoo.groupby('animal')['water_need'].sum()

animal
elephant    1650
tiger       1550
zebra        200
Name: water_need, dtype: int64

In [27]:
zoo = pd.DataFrame({
    'animal': ['elephant', 'elephant', 'elephant',
               'tiger', 'tiger', 'tiger', 'tiger', 'tiger',
               'zebra'],
    
    'uniq_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
    
    'water_need': [500, 600, 550, 300, 320, 330, 290, 310, 200]
})

zoo

     animal  uniq_id  water_need
0  elephant     1001         500
1  elephant     1002         600
2  elephant     1003         550
3     tiger     1004         300
4     tiger     1005         320
5     tiger     1006         330
6     tiger     1007         290
7     tiger     1008         310
8     zebra     1009         200

In [28]:
animal    uniq_id    water_need
elephant  1001       500
elephant  1002       600
elephant  1003       550
tiger     1004       300
tiger     1005       320
tiger     1006       330
tiger     1007       290
tiger     1008       310
zebra     1009       200

SyntaxError: invalid syntax (2173118351.py, line 1)

In [ ]:
result_group = df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

result_group

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [ ]:
result = df[['Fee', 'Discount']].agg(['min', 'max', 'mean'])

result

          Fee  Discount
min   20000.0     500.0
max   56000.0    2500.0
mean  31000.0    1512.5

In [ ]:
# Do both the agg and alternative to find: count
count1 = df['Value'].agg('count')
print(count1)

count2 = df[['Value']].count()
print(count2)

8
Value    8
dtype: int64

In [ ]:
# Do both the agg and alternative to find: max
max1 = df['Value'].agg('max')
print(max1)

max2 = df[['Value']].max()
print(max2)

50
Value    50
dtype: int64

In [ ]:
# Do both the agg and alternative to find: mean
mean1 = df['Value'].agg('mean')
print(f'Mean: {mean1}')

mean2 = df[['Value']].mean()
print(f'Mean: {mean2}')

Mean: 28.125
Mean: Value    28.125
dtype: float64

In [ ]:
df['Value'].agg('cumsum')

df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135
6    175
7    225

In [ ]:
# calculate the total sum of the Value column
total_sum = df['Value'].agg('sum')

print(f'Total Sum: {total_sum}')

# Alternative
total_sum1 = df[['Value']].sum()

print(total_sum1)

Total Sum: 225
Value    225
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35, 40, 50],
    'Fee': [20000, 25000, 26000, 22000, 24000, 35000, 40000, 56000],
    'Duration': ['30day', '40days', '35days', '40days', '60days', '60days', '50days', '60days'],
    'Discount': [1000, 2300, 1200, 2500, 2000, 2000, 500, 600]
}

df = pd.DataFrame(data)
df

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000
5        B     35  35000   60days      2000
6        A     40  40000   50days       500
7        B     50  56000   60days       600