In [22]:
zoo.groupby('animal')['water_need'].sum()

animal
elephant    1650
tiger       1550
zebra        200
Name: water_need, dtype: int64

In [23]:
result_Group = df.groupby('Category')[['Value', 'Fee', 'Discount']].aggregate('sum')

print(result_Group)

          Value     Fee  Discount
Category
A            95  109000      5800
B           130  139000      6300

In [24]:
result_group = df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

result_group

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [25]:
df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [26]:
zoo.groupby('animal')['water_need'].sum()

animal
elephant    1650
tiger       1550
zebra        200
Name: water_need, dtype: int64

In [27]:
zoo = pd.DataFrame({
    'animal': ['elephant', 'elephant', 'elephant',
               'tiger', 'tiger', 'tiger', 'tiger', 'tiger',
               'zebra'],
    
    'uniq_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
    
    'water_need': [500, 600, 550, 300, 320, 330, 290, 310, 200]
})

zoo

     animal  uniq_id  water_need
0  elephant     1001         500
1  elephant     1002         600
2  elephant     1003         550
3     tiger     1004         300
4     tiger     1005         320
5     tiger     1006         330
6     tiger     1007         290
7     tiger     1008         310
8     zebra     1009         200

In [28]:
animal    uniq_id    water_need
elephant  1001       500
elephant  1002       600
elephant  1003       550
tiger     1004       300
tiger     1005       320
tiger     1006       330
tiger     1007       290
tiger     1008       310
zebra     1009       200

SyntaxError: invalid syntax (2173118351.py, line 1)

In [ ]:
result_group = df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum'])

result_group

         Value     Fee Discount
           sum     sum      sum
Category
A           95  109000     5800
B          130  139000     6300

In [ ]:
result = df[['Fee', 'Discount']].agg(['min', 'max', 'mean'])

result

          Fee  Discount
min   20000.0     500.0
max   56000.0    2500.0
mean  31000.0    1512.5

In [ ]:
# Do both the agg and alternative to find: count
count1 = df['Value'].agg('count')
print(count1)

count2 = df[['Value']].count()
print(count2)

8
Value    8
dtype: int64

In [ ]:
# Do both the agg and alternative to find: max
max1 = df['Value'].agg('max')
print(max1)

max2 = df[['Value']].max()
print(max2)

50
Value    50
dtype: int64

In [ ]:
# Do both the agg and alternative to find: mean
mean1 = df['Value'].agg('mean')
print(f'Mean: {mean1}')

mean2 = df[['Value']].mean()
print(f'Mean: {mean2}')

Mean: 28.125
Mean: Value    28.125
dtype: float64

In [ ]:
df['Value'].agg('cumsum')

df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135
6    175
7    225

In [ ]:
# calculate the total sum of the Value column
total_sum = df['Value'].agg('sum')

print(f'Total Sum: {total_sum}')

# Alternative
total_sum1 = df[['Value']].sum()

print(total_sum1)

Total Sum: 225
Value    225
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35, 40, 50],
    'Fee': [20000, 25000, 26000, 22000, 24000, 35000, 40000, 56000],
    'Duration': ['30day', '40days', '35days', '40days', '60days', '60days', '50days', '60days'],
    'Discount': [1000, 2300, 1200, 2500, 2000, 2000, 500, 600]
}

df = pd.DataFrame(data)
df

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000
5        B     35  35000   60days      2000
6        A     40  40000   50days       500
7        B     50  56000   60days       600

In [4]:
# R-GLAB 386.4.4 - Pandas Aggregate Function Lab

import pandas as pd

# Create the DataFrame
data = {
    'Department': [
        'Sales', 'Sales', 'Sales', 'Sales', 'Sales', 'Sales',
        'Engineering', 'Engineering', 'Engineering', 'Engineering', 'Engineering',
        'HR', 'HR', 'HR', 'HR',
        'Marketing', 'Marketing', 'Marketing', 'Marketing', 'Marketing'
    ],

    'Employee': [
        'Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank',
        'Grace', 'Hannah', 'Ian', 'Jack', 'Karen',
        'Liam', 'Mona', 'Nathan', 'Olivia',
        'Paul', 'Quinn', 'Rachel', 'Sam', 'Tina'
    ],

    'Salary': [
        70000, 80000, 75000, 82000, 68000, 79000,
        110000, 120000, 115000, 105000, 125000,
        65000, 60000, 62000, 67000,
        72000, 78000, 85000, 69000, 74000
    ],

    'Bonus': [
        5000, 8000, 6000, 8500, 4500, 7500,
        12000, 15000, 13000, 11000, 16000,
        4000, 3000, 3500, 4200,
        5500, 7000, 9000, 5000, 6000
    ],

    'Performance_Score': [
        88, 92, 85, 90, 82, 89,
        95, 98, 94, 91, 99,
        78, 82, 80, 84,
        87, 91, 93, 83, 88
    ]
}

df = pd.DataFrame(data)

df.head(20)

     Department Employee  Salary  Bonus  Performance_Score
0         Sales    Alice   70000   5000                 88
1         Sales      Bob   80000   8000                 92
2         Sales  Charlie   75000   6000                 85
3         Sales    David   82000   8500                 90
4         Sales      Eva   68000   4500                 82
5         Sales    Frank   79000   7500                 89
6   Engineering    Grace  110000  12000                 95
7   Engineering   Hannah  120000  15000                 98
8   Engineering      Ian  115000  13000                 94
9   Engineering     Jack  105000  11000                 91
10  Engineering    Karen  125000  16000                 99
11           HR     Liam   65000   4000                 78
12           HR     Mona   60000   3000                 82
13           HR   Nathan   62000   3500                 80
14           HR   Olivia   67000   4200                 84
15    Marketing     Paul   72000   5500                 87
16    Marketing    Quinn   78000   7000                 91
17    Marketing   Rachel   85000   9000                 93
18    Marketing      Sam   69000   5000                 83
19    Marketing     Tina   74000   6000                 88

In [5]:
# Task 1: Calculate total, average, max values for salary in one command

df[['Salary']].agg(['sum', 'mean', 'max'])

         Salary
sum   1661000.0
mean    83050.0
max    125000.0

In [6]:
# Task 2: Calculate min, max and average across Salary and Bonus columns

df[['Salary', 'Bonus']].agg(['min', 'max', 'mean'])

        Salary    Bonus
min    60000.0   3000.0
max   125000.0  16000.0
mean   83050.0   7685.0

In [7]:
# Task 3: Calculate specific metrics for each column

df.groupby('Department').agg(
    {
        'Salary': ['mean', 'median'],
        'Performance_Score': ['max'],
        'Bonus': ['sum']
    }
)

                    Salary           Performance_Score  Bonus
                      mean    median               max    sum
Department
Engineering  115000.000000  115000.0                99  67000
HR            63500.000000   63500.0                84  14700
Marketing     75600.000000   74000.0                93  32500
Sales         75666.666667   77000.0                92  39500

In [8]:
# Task 4: For each department - average salary,
# highest performance score, total bonus paid

df.groupby('Department').agg(
    {
        'Salary': ['mean'],
        'Performance_Score': ['max'],
        'Bonus': ['sum']
    }
)

                    Salary Performance_Score  Bonus
                      mean               max    sum
Department
Engineering  115000.000000                99  67000
HR            63500.000000                84  14700
Marketing     75600.000000                93  32500
Sales         75666.666667                92  39500